let data = {
    "Windows": [
        {"name":"Driver Reviver 5.36.0.14", "link":""},
        {"name":"CrossFont 7.10", "link":""},
        {"name":"Viddly YouTube Downloader 5.0.269", "link":""},
        {"name":"S.O.S. Security Suite 1.1.0.0", "link":""},
        {"name":"Crow Translate 2.7.0", "link":""},
        {"name":"mks_vir 2020.10.13", "link":""},
        {"name":"Samsung Smart Switch 4.2.21013.13", "link":""},
        {"name":"Postbox 7.0.46", "link":""},
        {"name":"Advanced SystemCare 14.2.0.220", "link":""},
        {"name":"Advanced SystemCare Pro 14.2.0.220", "link":""},
        {"name":"Lansweeper 8.2.100.11", "link":""},
        {"name":"Allavsoft 3.23.3.7695", "link":""},
        {"name":"backiee - Wallpaper Studio 10 10.1.203.0", "link":""},
        {"name":"Windows Maps 10.2012.10.0", "link":""},
        {"name":"Action! 4.15.0", "link":""}
    ],
    "Linux": [
        {"name":"Crow Translate 2.7.0", "link":""},
        {"name":"Vivaldi 3.6", "link":""},
        {"name":"SEO SpyGlass 6.50.9", "link":""},
        {"name":"LinkAssistant 6.37.9", "link":""},
        {"name":"Rank Tracker 8.37.9", "link":""},
        {"name":"Tor Browser 10.0.9", "link":""},
        {"name":"GParted 1.2.0", "link":""},
        {"name":"Bitwarden 1.24.4", "link":""},
        {"name":"Mozilla Thunderbird 78.7.0", "link":""},
        {"name":"TeamViewer 15.14.3", "link":""},
        {"name":"OpenOffice 4.1.9", "link":""},
        {"name":"Mozilla Firefox 85.0", "link":""},
        {"name":"LosslessCut 3.31.1", "link":""},
        {"name":"PDF Split and Merge (PDFsam) Basic 4.2.2", "link":""},
        {"name":"Prey 1.9.9", "link":""}
    ],
    "Mac": [
        {"name":"Postbox 7.0.46", "link":""},
        {"name":"Vivaldi 3.6", "link":""},
        {"name":"SEO SpyGlass 6.50.9", "link":""},
        {"name":"LinkAssistant 6.37.9", "link":""},
        {"name":"Rank Tracker 8.37.9", "link":""},
        {"name":"Microsoft Edge 88.0.705.53", "link":""},
        {"name":"Opera GX 72.0.3815.487", "link":""},
        {"name":"Tor Browser 10.0.9", "link":""},
        {"name":"Speedify 10.9.1", "link":""},
        {"name":"AutoCAD 2021 dla Mac", "link":""},
        {"name":"Bitwarden 1.24.4", "link":""},
        {"name":"Cyberduck 7.8.2.34203", "link":""},
        {"name":"Remote Desktop Manager Free 2020.3.4.0", "link":""},
        {"name":"Remote Desktop Manager 2020.3.4.0", "link":""},
        {"name":"Mozilla Thunderbird 78.7.0", "link":""}
    ],
    "Android": [
        {"name":"Przegląd Sportowy 3.9", "link":""},
        {"name":"puchar świata piłki nożnej 3d 1.5.8", "link":""},
        {"name":"Race Simulator 3.00", "link":""},
        {"name":"Proste Stoper", "link":""},
        {"name":"LigaBET - Pronostici Calcio 3.2.2", "link":""},
        {"name":"Prognozy Piłkarskie Forebet 1.96", "link":""},
        {"name":"Element - Secure Messenger 1.0.14", "link":""},
        {"name":"Ordia 1.0.11", "link":""},
        {"name":"Zwift 1.0.61279", "link":""},
        {"name":"Candy Crush Saga 1.193.0.2", "link":""},
        {"name":"Yale Access 10.20.0", "link":""},
        {"name":"Figment 1.3.9", "link":""},
        {"name":"Angry Birds Journey 1.0.1", "link":""},
        {"name":"Mój BIK - bezpieczne finanse 1.0.2", "link":""},
        {"name":"Don't Crash 0.1", "link":""}
    ],
    "Games": [
        {"name":"Microsoft Solitaire Collection 4.9.1252", "link":""},
        {"name":"Roblox 2.462", "link":""},
        {"name":"Logyx Pack 21.00", "link":""},
        {"name":"FlightGear 2020.3.6", "link":""},
        {"name":"Quake Live", "link":""},
        {"name":"War Trigger 3", "link":""},
        {"name":"Rakard Kingdoms", "link":""},
        {"name":"Rail Nation", "link":""},
        {"name":"QuakeJS", "link":""},
        {"name":"WRC - FIA World Rally Championship 2010", "link":""},
        {"name":"League of Legends 11.1", "link":""},
        {"name":"Fallout - The Frontier 1.0.0", "link":""},
        {"name":"Minecraft 1.16.5", "link":""},
        {"name":"SolSuite Solitaire 2021 21.1", "link":""},
        {"name":"Scorched 3D 44.0", "link":""}
    ]
};